### PR TITLE
feat(voiceChatUtilities): run promises sequential

### LINKED ISSUE #18: VoiceChatUtilities
I know it is better to have the RestApi but would be very cool to have a toggle or something in the settings to do everything **instant**.
I also tried to remove the [* 500](https://github.com/D3SOX/vencord-userplugins/blob/a3f9f856e969da00907836144969e6f51ed225a8/voiceChatUtilities/index.tsx#L29) but still not instant :(

### PR DESCRIPTION
**Pull request by D3SOX**
Closes #18

### CODE REVIEW

**Comment by RobinRMC** [comment]
This will spam the API at a high rate and can result in an account termination, no?

**Comment by D3SOX** [comment]
Depends on if you use it in a vc with a lot of members, should probably add something that prevents you from doing

**Comment by D3SOX** [comment]
Added back a delay with settings for it

**Comment by D3SOX** [comment]
I've had it as milliseconds before but the slider looked really bad with those big numbers so I changed it to seconds

**Comment by RobinRMC** [comment]
Why can't you let the user input a delay, instead of using a slider?

**Comment by D3SOX** [comment]
That's definitely an option but I think I still prefer seconds with slider 0.5 range because it' easier to configure

**Comment by RobinRMC** [comment]
Per 0.5 seconds is actually a really good idea.

**Pull request merged**
