### PR TITLE
Add Playstation icon and activity to memberListActivities

### PR DESCRIPTION
**Pull request by verticalsync**
This is referring to #1, where @D3SOX said that we may need this for playstation as well, the code isn't really pretty if we want to continue using the ternary operator, but we can change that if needed.

### CODE REVIEW

**Comment by D3SOX** [comment]
Can't you do it like Spotify and Twitch further up. Would be cleaner I think,

**Comment by verticalsync** [comment]
> Can't you do it like Spotify and Twitch further up. Would be cleaner I think,

Sorry my brain is being retarded, hold on I'll fix something real quick.

**Comment by jaxellis** [comment]
Playstation gives an asset to use for icons btw. We can add a PS icon if we want as well.
https://github.com/D3SOX/vencord-userplugins/pull/4

**Comment by verticalsync** [comment]
Yeah I didn't get this to work properly (current code doesn't work, i messed up) so refer to what jaxellis said.

**Pull request closed without merging**
